---
- name: Make sure /etc/docker exists
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    mode: '0644'

- name: Set docker configuration
  ansible.builtin.set_fact:
    docker_config: "{{ docker_config | combine({item.key: item.value}) }}"
  when: item.value != ""
  with_dict: "{{ docker_options }}"

- name: Create the conf file /etc/docker/daemon.json
  ansible.builtin.copy:
    content: "{{ docker_config | to_nice_json }}\n"
    dest: /etc/docker/daemon.json
    mode: '0644'
  when: docker_config != {}
  notify: Restart docker
