---
- name: "[EL] Fail if distro is not supported nor tested"
  fail: msg="The role is designed only for RedHat/CentOS 7.2 or later"
  when: "ansible_distribution not in ('RedHat', 'CentOS') or {{ ansible_distribution_version | version_compare('7.2', '<') }}"

- name: "[EL] Add Docker yum repository"
  copy:
    src=files/docker.repo dest=/etc/yum.repos.d/docker.repo mode=0644

- name: "[EL] Perform common tasks"
  include: common.yml

# Setting up the docker0 bridge on Ubuntu 14.04 is done by literally changing
# a single line in /etc/default/docker. Unfortunately on EL and derivatives
# this means going through a systemd drop-in dance:
# 1) create /etc/systemd/system/docker.service.d
# 2) create custom.conf drop-in in said directory
# 3) notify systemd it should reload all units and restart Docker
- name: "[EL] Create systemd drop-in directory for Docker"
  file:
    path={{docker_dropin_dir}}
    state=directory
    mode=0755

- name: "[EL] Configure docker0 bridge"
  template:
    src=docker-dropin.conf.j2 dest={{docker_dropin_dir}}/custom.conf
  notify:
    - reload systemd
    - restart docker
