---
- name: "[EL] Fail if distro is not supported nor tested"
  fail: msg="The role is designed only for RedHat/CentOS 7.2 or later"
  when: "ansible_distribution not in ('RedHat', 'CentOS') or {{ ansible_distribution_version | version_compare('7.2', '<') }}"

- name: "[EL] Add Docker yum repository"
  copy:
    src=files/docker.repo dest=/etc/yum.repos.d/docker.repo mode=0644

- name: "[EL] Perform common tasks"
  include: common.yml

# Setup Docker Engine to take configuration options from environment files
# like we do on Ubuntu. This is the default for the docker-engine package in
# RHEL7 but *not* in the upstream package, so we have to override the provided
# systemd unit.
#
# See https://docs.docker.com/engine/admin/systemd/#custom-docker-daemon-options
# for more information.
- name: "[EL] Create systemd drop-in directory for Docker"
  file:
    path={{docker_dropin_dir}}
    state=directory
    mode=0755

- name: "[EL] Override Docker Engine startup parameters"
  copy:
    src=files/docker-dropin.conf dest={{docker_dropin_dir}}/custom.conf
  notify:
    - reload systemd
    - restart docker

- name: "[EL] Configure docker0 bridge"
  template:
    src=docker-network.conf.j2 dest=/etc/sysconfig/docker-network
  notify:
    - restart docker
