---
- name: "[Ubuntu] Fail if release is not supported"
  fail:
    msg="The role is designed only for Ubuntu 14.04"
  when: "{{ ansible_distribution_version | version_compare('14.04', '!=') }}"

- name: "[Ubuntu] Add docker apt repo"
  apt_repository:
    repo='deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main'
    state=present

- name: "[Ubuntu] Import the Docker repository key"
  apt_key:
    url=https://apt.dockerproject.org/gpg
    state=present
    id=2C52609D

- name: "[Ubuntu] Force an apt cache refresh"
  apt: update_cache=yes

- name: "[Ubuntu] Perform common tasks"
  include: common.yml

- name: "[Ubuntu] Configure docker0 bridge"
  lineinfile:
    dest: /etc/default/docker
    state: present
    insertafter: ^DOCKER_OPTS=.*
    line: "DOCKER_OPTS=\"$DOCKER_OPTS --bip={{docker_bridge_ip}}/24 \""
  notify:
    - restart docker
