---

- name: "[Ubuntu] Fail if release is not supported (Ubuntu version >= 16.04)"
  ansible.builtin.fail:
    msg: "The role is designed only for Ubuntu 16.04 or higher"
  when:
    - ansible_distribution_version is version('16.04', '<')

- name: Install docker requisites
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - software-properties-common

- name: "[Ubuntu] Import the Docker repository key"
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    id: 0EBFCD88

- name: "[Ubuntu] Add docker apt repo"
  ansible.builtin.apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
    state: present
  notify: "Refresh apt cache"


- name: "[Ubuntu] Perform common tasks"
  ansible.builtin.include_tasks: common.yml
