---
# handlers file for docker.ubuntu
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Start docker
  ansible.builtin.service:
    name: docker
    state: started

- name: Reload docker
  ansible.builtin.service:
    name: docker
    state: reloaded

- name: Restart docker
  ansible.builtin.service:
    name: docker
    state: restarted

- name: "Refresh apt cache"
  ansible.builtin.apt:
    update_cache: true
  changed_when: false
