---
# handlers file for docker.ubuntu
- name: reload systemd
  command: systemctl daemon-reload

- name: start docker
  service: name=docker state=started

- name: reload docker
  service: name=docker state=reloaded

- name: restart docker
  service: name=docker state=restarted
